### ISSUE TITLE
DWARFError while parsing mipsel libgcc.so

### ISSUE THREAD

**Issue by plafosse** [eliben/pyelftools#336] opened 2020-10-19 13:10 UTC
```
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from elftools.elf.elffile import ELFFile
   ...: elf_file = ELFFile(open('linux/mipsel/libgcc.so', 'rb'))
   ...: dwarf_info = elf_file.get_dwarf_info()
   ...: for cu in dwarf_info.iter_CUs():
   ...:     for die in cu.iter_DIEs():
   ...:         die.offset
   ...:
---------------------------------------------------------------------------
DWARFError                                Traceback (most recent call last)
<ipython-input-1-a8cda90efc13> in <module>
      3 dwarf_info = elf_file.get_dwarf_info()
      4 for cu in dwarf_info.iter_CUs():
----> 5     for die in cu.iter_DIEs():
      6         die.offset
      7

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/compileunit.py in iter_DIEs(self)
    103             Note that null DIEs will also be returned.
    104         """
--> 105         return self._iter_DIE_subtree(self.get_top_DIE())
    106
    107     def iter_DIE_children(self, die):

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/compileunit.py in get_top_DIE(self)
     92                 cu=self,
     93                 stream=self.dwarfinfo.debug_info_sec.stream,
---> 94                 offset=self.cu_die_offset)
     95
     96         self._dielist.insert(0, top)

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/die.py in __init__(self, cu, stream, offset)
     92         self._parent = None
     93
---> 94         self._parse_DIE()
     95
     96     def is_null(self):

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/die.py in _parse_DIE(self)
    171             return
    172
--> 173         abbrev_decl = self.cu.get_abbrev_table().get_abbrev(self.abbrev_code)
    174         self.tag = abbrev_decl['tag']
    175         self.has_children = abbrev_decl.has_children()

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/compileunit.py in get_abbrev_table(self)
     76         if self._abbrev_table is None:
     77             self._abbrev_table = self.dwarfinfo.get_abbrev_table(
---> 78                 self['debug_abbrev_offset'])
     79         return self._abbrev_table
     80

~/Library/Python/3.7/lib/python/site-packages/elftools/dwarf/dwarfinfo.py in get_abbrev_table(self, offset)
    132         dwarf_assert(
    133             offset < self.debug_abbrev_sec.size,
--> 134             "Offset '0x%x' to abbrev table out of section bounds" % offset)
    135         if offset not in self._abbrevtable_cache:
    136             self._abbrevtable_cache[offset] = AbbrevTable(

~/Library/Python/3.7/lib/python/site-packages/elftools/common/utils.py in dwarf_assert(cond, msg)
     81     """ Assert that cond is True, otherwise raise DWARFError(msg)
     82     """
---> 83     _assert_with_exception(cond, msg, DWARFError)
     84
     85

~/Library/Python/3.7/lib/python/site-packages/elftools/common/utils.py in _assert_with_exception(cond, msg, exception_type)
    107 def _assert_with_exception(cond, msg, exception_type):
    108     if not cond:
--> 109         raise exception_type(msg)

DWARFError: Offset '0x1bc5' to abbrev table out of section bounds

In [2]: import elftools

In [3]: elftools.__version__
Out[3]: '0.26'

In [4]:```

**Comment by plafosse** [comment] 2020-10-19 13:12
That'll teach me to create an issue without hitting preview first :) 
Here is the file:
[libgcc.so.zip](https://github.com/eliben/pyelftools/files/5401978/libgcc.so.zip)

**Comment by rupran** [comment] 2020-10-25 12:56
I can confirm that this still breaks on the current master, but I'm not an expert with DWARF... @sevaa or @mdmillerii, would you mind taking a look?

**Comment by eliben** [comment] 2020-10-26 15:58
I double checked that this isn't a regression since the last release, and in fact the code firing this error is very old (from 2011-2012).

I suspect pyelftools is being more pedantic than other tools here; binutils and other tools I checked ignore such problems (or at best produce a warning).

**Comment by sevaa** [comment] 2020-10-26 18:48
It's a bug in `pyelftools`. The sections are compressed, but `_read_dwarf_section` under elffile.py uses the raw size instead of uncompressed size to initialize the section size in the DebugSectionDescriptor constructor call.

Replace line 620 with

    size=section._decompressed_size,

and it will do the trick. `_decompressed_size` for ELF section objects is initialized to a copy of raw size for decompressed sections too.

**Comment by sevaa** [comment] 2020-10-26 19:46
PR #339.

**Comment by eliben** [comment] 2020-10-27 12:42
Thanks for investigating and sending a fix, @sevaa

**Comment by eliben** [comment] 2020-10-27 12:45
Closing this one as fixed. Opened #340 to track further support of compressed sections.

**Closed by eliben** 2020-10-27 12:45 UTC
